const THEMES = {
  football: {
    key: 'football',
    name: 'Football',
    avatar: '⚽',
    bgStyle: 'linear-gradient(135deg, #E8F5E9 0%, #F1F8E9 40%, #FFFDE7 100%)',
    accent: '#4CAF50',
    accentLight: '#C8E6C9',
    accentDark: '#2E7D32',
    headerGradient: 'linear-gradient(135deg, #4CAF50, #66BB6A, #43A047)',
    stickers: ['⚽', '🏆', '🥅', '🏅', '💪', '👟', '🎯', '🌟', '🔥', '⭐', '🏟️', '🦁', '💚', '✨', '🎉', '👑'],
    badgeIcons: { diamond: '🏆', gold: '🥇', silver: '🥈', bronze: '🥉' },
    decorEmojis: ['⚽', '🥅', '👟'],
    streakIcon: '⚽',
    egg: { name: 'Pitch Egg', color: '#A5D6A7', motif: '○', motifColor: '#FFFFFF', motifCount: 4 },
  },
  dinosaur: {
    key: 'dinosaur',
    name: 'Dinosaur',
    avatar: '🦕',
    bgStyle: 'linear-gradient(135deg, #EDE7F6 0%, #E8EAF6 40%, #E1F5FE 100%)',
    accent: '#7E57C2',
    accentLight: '#D1C4E9',
    accentDark: '#4527A0',
    headerGradient: 'linear-gradient(135deg, #7E57C2, #9575CD, #5C6BC0)',
    stickers: ['🦕', '🦖', '🌋', '🥚', '🦴', '🌿', '💎', '⭐', '🔥', '🌟', '🪨', '🌴', '💜', '✨', '🎉', '👑'],
    badgeIcons: { diamond: '👑', gold: '🦖', silver: '🦕', bronze: '🥚' },
    decorEmojis: ['🦕', '🌋', '🦴'],
    streakIcon: '🦖',
    egg: { name: 'Mint Egg', color: '#80CBC4', motif: '•', motifColor: '#00695C', motifCount: 4 },
  },
  space: {
    key: 'space',
    name: 'Space',
    avatar: '🚀',
    bgStyle: 'linear-gradient(135deg, #E3F2FD 0%, #E8EAF6 40%, #EDE7F6 100%)',
    accent: '#3F51B5',
    accentLight: '#C5CAE9',
    accentDark: '#283593',
    headerGradient: 'linear-gradient(135deg, #3F51B5, #5C6BC0, #7986CB)',
    stickers: ['🚀', '🪐', '🌟', '✨', '🌙', '☄️', '👨‍🚀', '🛸', '⭐', '🌌', '🔭', '🌍', '💫', '🎆', '🎇', '👽'],
    badgeIcons: { diamond: '🌌', gold: '🚀', silver: '🪐', bronze: '⭐' },
    decorEmojis: ['🚀', '🪐', '⭐'],
    streakIcon: '🚀',
    egg: { name: 'Cosmic Egg', color: '#9FA8DA', motif: '✦', motifColor: '#FFFFFF', motifCount: 4 },
  },
  unicorn: {
    key: 'unicorn',
    name: 'Unicorn',
    avatar: '🦄',
    bgStyle: 'linear-gradient(135deg, #FCE4EC 0%, #F3E5F5 40%, #E1BEE7 100%)',
    accent: '#EC407A',
    accentLight: '#F8BBD0',
    accentDark: '#AD1457',
    headerGradient: 'linear-gradient(135deg, #EC407A, #F06292, #BA68C8)',
    stickers: ['🦄', '🌈', '✨', '💖', '🌸', '🦋', '⭐', '🌟', '💫', '🎀', '🧚', '💕', '🌺', '🍭', '🎈', '👑'],
    badgeIcons: { diamond: '👑', gold: '🦄', silver: '🌈', bronze: '🌸' },
    decorEmojis: ['🦄', '🌈', '✨'],
    streakIcon: '🦄',
    egg: { name: 'Rainbow Egg', color: '#CE93D8', motif: '✦', motifColor: '#FFFFFF', motifCount: 4 },
  },
  mermaid: {
    key: 'mermaid',
    name: 'Mermaid',
    avatar: '🧜‍♀️',
    bgStyle: 'linear-gradient(135deg, #E0F7FA 0%, #E1F5FE 40%, #E3F2FD 100%)',
    accent: '#00ACC1',
    accentLight: '#B2EBF2',
    accentDark: '#006064',
    headerGradient: 'linear-gradient(135deg, #00ACC1, #26C6DA, #4DD0E1)',
    stickers: ['🧜‍♀️', '🐚', '🐠', '🐟', '🐬', '🌊', '⭐', '🌟', '💙', '✨', '🐙', '🦀', '🪸', '🫧', '🏖️', '👑'],
    badgeIcons: { diamond: '👑', gold: '🧜‍♀️', silver: '🐚', bronze: '🐟' },
    decorEmojis: ['🧜‍♀️', '🐚', '🌊'],
    streakIcon: '🌊',
    egg: { name: 'Bubble Egg', color: '#80DEEA', motif: '○', motifColor: '#FFFFFF', motifCount: 4 },
  },
  robot: {
    key: 'robot',
    name: 'Robot',
    avatar: '🤖',
    bgStyle: 'linear-gradient(135deg, #ECEFF1 0%, #CFD8DC 40%, #B0BEC5 100%)',
    accent: '#607D8B',
    accentLight: '#CFD8DC',
    accentDark: '#263238',
    headerGradient: 'linear-gradient(135deg, #455A64, #607D8B, #78909C)',
    stickers: ['🤖', '⚙️', '🔋', '💡', '⚡', '🔩', '🛠️', '📡', '🛰️', '🎛️', '💻', '🔌', '🧲', '🔦', '⭐', '🏆'],
    badgeIcons: { diamond: '🏆', gold: '🤖', silver: '⚙️', bronze: '🔋' },
    decorEmojis: ['🤖', '⚙️', '⚡'],
    streakIcon: '⚡',
    egg: { name: 'Circuit Egg', color: '#B0BEC5', motif: '◆', motifColor: '#263238', motifCount: 4 },
  },
  superhero: {
    key: 'superhero',
    name: 'Superhero',
    avatar: '🦸',
    bgStyle: 'linear-gradient(135deg, #FFEBEE 0%, #FFE0B2 40%, #FFF9C4 100%)',
    accent: '#E53935',
    accentLight: '#FFCDD2',
    accentDark: '#B71C1C',
    headerGradient: 'linear-gradient(135deg, #E53935, #EF5350, #FF7043)',
    stickers: ['🦸', '🦸‍♀️', '🦹', '💥', '⚡', '🛡️', '💪', '🌟', '⭐', '🔥', '✨', '🦇', '🕷️', '🏆', '👑', '💫'],
    badgeIcons: { diamond: '🏆', gold: '🦸', silver: '💪', bronze: '🛡️' },
    decorEmojis: ['🦸', '💥', '⚡'],
    streakIcon: '💥',
    egg: { name: 'Hero Egg', color: '#EF9A9A', motif: '★', motifColor: '#FFFFFF', motifCount: 4 },
  },
  artist: {
    key: 'artist',
    name: 'Artist',
    avatar: '🎨',
    bgStyle: 'linear-gradient(135deg, #FFF3E0 0%, #FCE4EC 40%, #F3E5F5 100%)',
    accent: '#FF7043',
    accentLight: '#FFCCBC',
    accentDark: '#BF360C',
    headerGradient: 'linear-gradient(135deg, #FF7043, #FF8A65, #FFAB91)',
    stickers: ['🎨', '🖌️', '🖍️', '✏️', '📝', '🌈', '✨', '🎭', '🖼️', '🌟', '💫', '🎪', '🎵', '💖', '🎀', '👑'],
    badgeIcons: { diamond: '🏆', gold: '🎨', silver: '🖌️', bronze: '🖍️' },
    decorEmojis: ['🎨', '🖌️', '🌈'],
    streakIcon: '🎨',
    egg: { name: 'Paint Egg', color: '#FFAB91', motif: '✦', motifColor: '#FFFFFF', motifCount: 4 },
  },
  animals: {
    key: 'animals',
    name: 'Animals',
    avatar: '🐾',
    bgStyle: 'linear-gradient(135deg, #FFF8E1 0%, #F1F8E9 40%, #E8F5E9 100%)',
    accent: '#8D6E63',
    accentLight: '#D7CCC8',
    accentDark: '#4E342E',
    headerGradient: 'linear-gradient(135deg, #8D6E63, #A1887F, #BCAAA4)',
    stickers: ['🐾', '🐶', '🐱', '🐰', '🦊', '🐻', '🐼', '🦁', '🐯', '🐮', '🐷', '🐵', '🐨', '🐭', '🦒', '🐘'],
    badgeIcons: { diamond: '🏆', gold: '🦁', silver: '🐻', bronze: '🐾' },
    decorEmojis: ['🐾', '🐱', '🐶'],
    streakIcon: '🐾',
    egg: { name: 'Cozy Egg', color: '#FFCC80', motif: '🐾', motifColor: '#5D4037', motifCount: 4 },
  },
}

export const THEME_LIST = Object.values(THEMES)

export function getTheme(key) {
  return THEMES[key] || THEMES.football
}

export default THEMES
