import { THEMES } from '../lib/themes'
import AnimatedRasterBanner from './AnimatedRasterBanner'
import BannerPet from './BannerPet'
import { EFFECT_BY_THEME } from './banner-effects'

const BANNER_IMAGES = {
  rugby: '/theme-banners/rugby.png',
  ocean: '/theme-banners/ocean.png',
  animals: '/theme-banners/animals.png',
  football: '/theme-banners/football.png',
  dinosaur: '/theme-banners/dinosaur.png',
  unicorn: '/theme-banners/unicorn.png',
  rocket: '/theme-banners/rocket.png',
  princess: '/theme-banners/princess.png',
  garden: '/theme-banners/garden.png',
  robot: '/theme-banners/robot.png',
  magic: '/theme-banners/magic.png',
  train: '/theme-banners/train.png',
  fairy: '/theme-banners/fairy.png',
  bear: '/theme-banners/bear.png',
  deer: '/theme-banners/deer.png',
  elephant: '/theme-banners/elephant.png',
  fox: '/theme-banners/fox.png',
}

const BANNER_DIMENSIONS = {
  rugby: [1851, 844],
  ocean: [2028, 542],
  animals: [2099, 475],
  football: [1898, 829],
  dinosaur: [2004, 554],
  unicorn: [2031, 545],
  rocket: [2091, 746],
  princess: [2045, 607],
  garden: [1747, 715],
  robot: [2030, 566],
  magic: [2085, 749],
  train: [2080, 750],
  fairy: [2038, 559],
  bear: [2109, 526],
  deer: [2172, 724],
  elephant: [2172, 724],
  fox: [2172, 724],
}

// WebP variants generated by `scripts/generate-banner-webp.mjs` at three widths.
// Browser picks the smallest variant that satisfies the rendered size — so a
// phone fetches ~5 KB instead of the 1.5 MB PNG source.
const WEBP_WIDTHS = [376, 768, 1500]

function buildWebpSrcSet(themeKey) {
  return WEBP_WIDTHS.map((w) => `/theme-banners/${themeKey}-${w}w.webp ${w}w`).join(', ')
}

// Tells the browser the rendered width per viewport so it can pick the right
// variant. Mobile takes the full viewport width; tablet+ caps at the page max.
const BANNER_SIZES = '(max-width: 768px) 100vw, 768px'

export default function ThemeBannerArt({
  themeKey = 'animals',
  height,
  animated = true,
  favoritePet = null,
  // Where the raster anchors when object-fit: cover crops vertically.
  // 'center' (default) is fine for Board's tall aspect; PrintSheet's wide
  // 14:1 strip cuts character heads, so it passes 'center top' to keep
  // faces visible.
  objectPosition,
  imageScale,
  autoHeight = false,
  autoHeightScale = 1,
  borderRadius = 24,
  sizes = BANNER_SIZES,
  // Pass 'lazy' when many banners render at once (theme picker grid,
  // PetGallery banner backgrounds). Default 'eager' for the active Board
  // banner which is on the critical path.
  loading = 'eager',
}) {
  const image = BANNER_IMAGES[themeKey]
  const theme = THEMES[themeKey] || THEMES.animals
  const label = theme?.label || 'Animals'
  const effect = EFFECT_BY_THEME[themeKey] || 'petals'

  if (!image) return null

  // BannerPet wants to anchor to the bottom-right of the banner — wrap in a
  // relative container so absolute positioning is scoped to this banner only.
  // height is sometimes a CSS clamp string (e.g. "clamp(136px, 22vw, 188px)"),
  // so we can't reliably parse a numeric height to gate showing the pet on
  // tiny banners. Instead, BannerPet itself bails on size<32 and we never
  // pass a tiny size from here.
  //
  // CRITICAL: the relative wrapper must own the height. PrintSheet places
  // this component in a `flex items-stretch` row with a fixed mm height,
  // and a wrapper without an inline height collapses to 0 inside that
  // flex parent — which makes the entire banner disappear from the print
  // sheet. Pass `height` through to the wrapper, then tell AnimatedRasterBanner
  // to fill 100% of it.
  const dimensions = BANNER_DIMENSIONS[themeKey] || BANNER_DIMENSIONS.animals
  const resolvedHeight = autoHeight ? undefined : height ?? 160
  const scaledHeight = Math.max(1, dimensions[1] * autoHeightScale)
  const aspectRatio = autoHeight ? `${dimensions[0]} / ${scaledHeight}` : undefined
  const resolvedImageScale = imageScale ?? (autoHeightScale < 1 ? 1.06 : 1.03)
  return (
    <div className="relative w-full" style={{ height: resolvedHeight, aspectRatio }}>
      <AnimatedRasterBanner
        source={image}
        webpSrcSet={buildWebpSrcSet(themeKey)}
        sizes={sizes}
        loading={loading}
        height="100%"
        borderRadius={borderRadius}
        animated={animated}
        effect={effect}
        themeColors={{ accent: theme.accent, deeper: theme.deeper }}
        accessibilityLabel={`${label} theme banner`}
        objectPosition={objectPosition}
        imageScale={resolvedImageScale}
      />
      <BannerPet emoji={favoritePet?.emoji} animated={animated} />
    </div>
  )
}
